### ISSUE TITLE
iOS cut off view

### ISSUE THREAD

**Issue by zbranzov** [Telerik-Verified-Plugins/AdMob-DemoApp#1]
Eddy, please update the kendo version to 2014.3.1316. It fixes cut off footer.

 ![Image](http://plugins.telerik.com/images/default-source/plugins/AdMob/ios-screenshot-1---banner-at-top.tmb-plugin-scr.png?sfvrsn=3)

**Comment by EddyVerbruggen** [comment]
Ha Zdravko, thanks for letting me know. And you're right: the Kendo update fixes the banner pushing the nav bar out of the view. Much better! New screenshots have been published: http://plugins.telerik.com/plugin/admob
